services:
  chat-app:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    container_name: chat-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ENV=local
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - MCP_SERVER_WEATHER_URL=http://weather-app:8001/mcp
      - MCP_SERVER_GOOGLE_URL=http://google-app:8003/mcp
      - POSTGRES_DATABASE_URL=postgresql://postgres:postgres@postgres:5432/my-personal-ai
      - QDRANT_URL=http://qdrant:6333
      - REDIS_URL=redis://redis:6379
    ports:
      - "8000:8000"
    networks:
      - my-personal-ai-local

networks:
  my-personal-ai-local:
    external: true
